### ISSUE TITLE
readiness check in streams mode support

### ISSUE THREAD

**Issue by difabion** [benthosdev/benthos-helm-chart#11]
Under normal operation, benthos' readiness is evaluated by checking the endpoint `/ready` [as defined here](https://github.com/Jeffail/benthos#health-checks).  

The behavior is a bit different in streams mode, however:

Given a configMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: benthos-streams
data:
  hello.yaml: |
    input:
      generate:
        mapping: root = "hello"
        interval: 5s
        count: 0
    output:
      stdout:
        codec: lines
  aaaaa.yaml: |
    input:
      generate:
        mapping: root = "AAAAAAAAAA"
        interval: 2s
        count: 0
    output:
      stdout:
        codec: lines
```
readiness endpoints are created at
```
/aaaaa/ready
/hello/ready
```
The readinessProbe object ([`spec.template.spec.containers[].readinessProbe`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core)) only supports one probe, which would prevent sufficient checking to ensure all pipelines are connected.

Currently the `readinessProbe` is set to the `livenessProbe` endpoint, potentially returning a false positive.  This should be reworked, hopefully with a strategy that includes all streams endpoints.
