### ISSUE TITLE
Values.config not configurable

### ISSUE THREAD

**Issue by lovuikeng** [benthosdev/benthos-helm-chart#44]
This part of the logic, [https://github.com/benthosdev/benthos-helm-chart/blob/main/templates/configmap.yaml#L31](url) not picking up config contents defined in _Values.config_ if streams.enabled is true, works if changed to `{{- if and .Values.config (ne .Values.streams.enabled false) }}`

**Comment by difabion** [comment]
For clarity, could you describe what you're putting in the `config` block when streams is enabled?

**Comment by lovuikeng** [comment]
here is what I have
```
# /benthos.yaml configuration
config: |-
  logger:
    level: TRACE
    format: logfmt
    add_timestamp: true
    static_fields:
      '@service': benthos
```
