### ISSUE TITLE
protobuf files in the extra volumes

### ISSUE THREAD

**Issue by Demmyart** [benthosdev/benthos-helm-chart#56]
Hi, I'm trying to use the processor as follows:

```  # pipeline:
    #   processors:
    #     - protobuf:
    #         operator: to_json
    #         message: FillReport
    #         import_paths: [ protobuf ]
``` 

So, I have configmap which is mounted as a volume then:

```
  extraVolumes: 
    - name: proto-vol
      configMap:
        name: protobuf

  extraVolumeMounts:
    - name: proto-vol
      mountPath: /protobuf
```

And after that I'm getting the following error: 
`level=error msg="Failed to create stream (fill_report_stream): failed to init processor <no label> path root.pipeline.processors.0: ..2023_11_20_13_23_29.2531302976/FillReport.proto:4:9: symbol \"FillReport\" already defined at FillReport.proto:4:9" @service=benthos`

Inside of the container, I'm getting the folder structure with multiple links:
```
45341956 drwxr-xr-x    2 root     root            30 Nov 20 20:01 ..2023_11_20_20_01_05.1721020983
43088997 lrwxrwxrwx    1 root     root            32 Nov 20 20:01 ..data -> ..2023_11_20_20_01_05.1721020983
43089266 lrwxrwxrwx    1 root     root            23 Nov 20 20:01 FillReport.proto -> ..data/FillReport.proto
```
Should we actually do this manipulation? What should I do to pass my proto file to the processor?
