### ISSUE TITLE
Probes failed when basic_auth is enabled

### ISSUE THREAD

**Issue by tbnguyen1407** [benthosdev/benthos-helm-chart#73]
**Version**

2.0.1

**Problem**

Defining `basic_auth` config will fail liveness and readiness probes. Pods will keep getting killed.

**Reproduction**

Deploy with custom values file:

```
~ values.yaml ~
...
http:
  basic_auth:
    enabled: true
    username: <username>
    password_hash: <password_hash>
```

Liveness and readiness probes will fail with status code `401 (Unauthorized)`

**Notes**

The probes probably need to check if `http.basic_auth` is configured and set `<probe>.httpGet.httpHeaders` accordingly.

Alternatively, the probes can be exposed to `values.yaml` so they can be customized.
