### ISSUE TITLE
ServiceMonitor not working when tls/auth is enabled

### ISSUE THREAD

**Issue by tbnguyen1407** [benthosdev/benthos-helm-chart#74]
**Problem**

When tls/auth is enabled, ServiceMonitor is not working due to missing `scheme: https` and `basicAuth` config for endpoint.

**Reproduction**

Deploy with custom values file

```
~ values.yaml ~
http:
  enabled: true
  cert_file: /etc/tls/benthos/cert.pem
  key_file: /etc/tls/benthos/key.pem
  basic_auth:
    username: <username>
    password_hash: <password_hash>

extraVolumes:
  - name: benthos-tls-vol
    secret:
      secretName: benthos-tls-secret

extraVolumeMounts:
  - name: benthos-tls-vol
    mountPath: /etc/tls/benthos

serviceMonitor:
  enabled: true
```

**Notes**

ServiceMonitor resource endpoint `scheme` and `basicAuth` should be configurable.
