### ISSUE TITLE
How to set the config file

### ISSUE THREAD

**Issue by FerroEduardo** [benthosdev/benthos-helm-chart#82]
How am I supposed to set my benthos config file to the chart? Since [this change](https://github.com/benthosdev/benthos-helm-chart/commit/b0d46fbe9d6e8ffcb7145acfe67e8537deae2ab2#diff-a8e9707baf626958aeec410369c5286199d18c17075ad924e7799db64da8c826L27-R29)/v2.1.0, I am unable to set using `--set-file config=./path/config.yaml`.

I also tried to set using cat, but no success:
```bash
rawConfigFile=$(cat my-config.yaml)

helm upgrade --install my-service benthos/benthos \
    --version 2.1.0 \
    -n my-namespace \
    --set config="$rawConfigFile"
```

> Generated config file
```yaml
http:
  address: 0.0.0.0:4195
  cors:
    enabled: false
  debug_endpoints: false
  enabled: true
  root_path: /benthos
-
  input:
    http_server:
      path: /poc
  output:
    broker:
      outputs:
        - stdout:
            codec: lines
        - sync_response: {}
```
