### ISSUE TITLE
values.yaml behavior changed

### ISSUE THREAD

**Issue by FerroEduardo** [benthosdev/benthos-helm-chart#83]
# Problem

> Both bugs bellow use `--set-file config=./path/config.yaml` to set the config file
1. A `-` is inserted in ConfigMap when replacing the config file by the helm template, making unreadable for Benthos
    - <details>
        <summary>Example</summary>
        
        ```
        http:
        address: 0.0.0.0:4195
        cors:
            enabled: false
        debug_endpoints: false
        enabled: true
        root_path: /benthos
        -
        input:
            http_server:
            path: /poc

        output:
            broker:
            outputs:
                - stdout:
                    codec: lines
                - sync_response: {}
        ```
    </details>

2. Custom config files that have **any extra space or blank line** are are converted to a raw string instead of being converted to YAML
    - <details>
        <summary>Example</summary>

        ```yaml
        http:
          address: 0.0.0.0:4195
          cors:
            enabled: false
          debug_endpoints: false
          enabled: true
          root_path: /benthos
        "input:\n  http_server:\n    path: /poc\n   \npipeline:\n  processors:\n    - noop:
          {}\n    \noutput:\n  broker:\n    outputs:\n      - stdout:\n          codec: lines\n
          \     - sync_response: {}\n"
        ```
    </details>

- The bugs were observed in versions in `2.1.0` and `2.1.1`.
- The unit tests (configuration_test.yaml) also fail if the bug #2 is reproduced

# Cause

This probably happended in this [commit](https://github.com/benthosdev/benthos-helm-chart/commit/b0d46fbe9d6e8ffcb7145acfe67e8537deae2ab2#diff-a8e9707baf626958aeec410369c5286199d18c17075ad924e7799db64da8c826L27-R29), which removed the `tpl` and now it is not possible to set the config using `--set-file config=./path/config.yaml`

------

A POC with more details and outputs can be found at this [repository](https://github.com/FerroEduardo/poc-benthos-helm-chart-bug)

Related: #82
