### ISSUE TITLE
Cronjob version configurable

### ISSUE THREAD

**Issue by acevedomiguel** [benthosdev/benthos-helm-chart#88]
I'm using the latest version of EKS on AWS and wanted to deploy some jobs on benthos.

It seems to try to create a `batch/v1beta1`, but the latest version of EKS has `batch/v1`. There is any way to configure this? 

```
Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/benthos-streams configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n'
```

let me know if you need more information

**Comment by charlie-haley** [comment]
Hey, thanks for raising this! 

Could you send me an examples of the values you're using with the Helm Chart?

**Comment by acevedomiguel** [comment]
Hi Charlie, thanks for your answer, here is my values.yaml
```yaml
deployment:
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  annotations: {}
  terminationGracePeriodSeconds: 60
  rolloutConfigMap: true

  readinessProbe:
    failureThreshold: 1
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
    httpGet:
      path: /ready
      port: http
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
    httpGet:
      path: /ping
      port: http
commonLabels: {}

image:
  repository: 'jeffail/benthos'
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podSecurityContext:
  {}

securityContext:
  {}

service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: http
  protocol: TCP

  extraPorts:

ingress:
  enabled: false
  className: ''
  annotations:
    {}
  hosts: []
  tls: []

env: []

envFrom:
  []

resources:
  {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget:
  enabled: false
  
initContainers: []

updateStrategy: {}

extraVolumes:
  []

extraVolumeMounts:
  []

streams:
  enabled: false
  streamsConfigMap: 'benthos-streams' # refers to ConfigMap in streamconfig.yml
  api:
    enable: true

http:
  # Disabling HTTP server will prevent service and ingress objects from being created.
  enabled: true
  address: '0.0.0.0:4195'
  root_path: '/benthos'
  debug_endpoints: false
  cors:
    enabled: false

serviceMonitor:
  enabled: false
  interval: '10s'
  scheme: http

command: []

args: []

watch: false

topologySpreadConstraints: []

config: {}
```

**Comment by acevedomiguel** [comment]
the base example works right out of the box
```yaml
input:
  generate:
    mapping: root = "woof"
    interval: 30s
    count: 0

buffer:
  memory: {}

pipeline:
  processors: []

output:
  stdout:
    codec: lines
```

but once we want to create a real-world processor it returns the error mentioned:
I removed the processors and outputs on this example to simplify, the error it's by just trying to setup a sqs input.
```yaml
input:
  label: "raw_values_nats_sqs"
  aws_sqs: 
    url: "https://sqs.ap-northeast-1.amazonaws.com/1234567890/MySqs"
    region: "ap-southeast-1"
    max_number_of_messages: 10

pipeline:
  processors: []

output:
  stdout:
    codec: lines
```
